#!/usr/bin/env bash
if [ ! -f debian-10.13.26-20240519-openstack-amd64.qcow2 ]; then
  wget https://cdimage.debian.org/cdimage/openstack/archive/10.13.26-20240519/debian-10.13.26-20240519-openstack-amd64.qcow2
fi

HOSTID=106
PubLicIP=192.168.11.200

cp debian-10.13.26-20240519-openstack-amd64.qcow2 debian-10.13.26-20240519-proxmox-amd64.qcow2

# Create a VM
qm create 9110 --name gateway-01 --memory 2048 --cores 2

# Import the disk in qcow2 format (as unused disk) 
qm importdisk 9110 debian-10.13.26-20240519-proxmox-amd64.qcow2 local-lvm -format raw

# Attach the disk to the vm using VirtIO SCSI
qm set 9110 --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-9110-disk-0

# Important settings
qm set 9110 --ide2 local-lvm:cloudinit --boot c --bootdisk scsi0 --serial0 socket --serial1 socket --vga virtio

# The initial disk is only 2GB, thus we make it larger
qm resize 9110 scsi0 +30G

# user authentication for 'debian' user (optional password)
qm set 9110 --ciuser debian --cipassword debian

# Set the IP configuration for net0
qm set 9110 --ipconfig0 ip=${PubLicIP}/24,gw=192.168.11.1
qm set 9110 --net0 model=virtio,bridge=vmbr0
qm set 9110 --nameserver 1.1.1.1

# Set the IP configuration for net1
qm set 9110 --ipconfig1 ip=192.168.8.1/24
qm set 9110 --net1 model=virtio,bridge=vmbr8

# Set keyboard layout to 'jp'
qm set 9110 --keyboard ja

# Create the snippets directory if it doesn't exist
mkdir -p /var/lib/vz/snippets

# Add cloud-init user data to run the setup script
cat <<EOF > /var/lib/vz/snippets/vm-setup.yaml
#cloud-config
users:
  - name: debian
    passwd: $(openssl passwd -1 debian)
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
runcmd:
  - echo "Starting vm-setup.sh" > /home/debian/cloudinit-status.txt
  - echo "update and install package" > /home/debian/cloudinit-status.txt
  - apt-get update && apt-get upgrade -y
  - apt-get install ssh vim tmux curl ntp -y
  - echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections
  - echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections
  - sudo DEBIAN_FRONTEND=noninteractive apt install -y iptables-persistent
  - systemctl enable ntp && systemctl start ntp
  - systemctl enable ssh && systemctl start ssh
  - echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
  - echo "Setting iptables" > /home/debian/cloudinit-status.txt
  - echo '1' > /proc/sys/net/ipv4/ip_forward
  - |
    cat <<FIREWALL | tee -a /etc/iptables/rules.v4
    # Generated by xtables-save v1.8.2
    *nat
    -A POSTROUTING -o eth0 -j MASQUERADE
    COMMIT

    *filter
    -A INPUT -i lo -j ACCEPT
    -A INPUT -i eth0 -p tcp -m tcp --dport 22 -j ACCEPT
    -A INPUT -i eth0 -p tcp -m tcp --dport 80 -j ACCEPT
    -A INPUT -i eth0 -p tcp -m tcp --dport 443 -j ACCEPT
    -A INPUT -i eth0 -p tcp -m tcp --dport 6443 -j ACCEPT
    -A INPUT -i eth0 -p icmp -j ACCEPT
    -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    -A INPUT -i eth0 -j DROP
    COMMIT
    FIREWALL
  - iptables-restore < /etc/iptables/rules.v4
  - echo "change hostname" > /home/debian/cloudinit-status.txt

  - echo "@reboot echo 'Hello' > /root/test.txt 2>&1" | crontab -

  - sudo hostnamectl set-hostname gateway-01  && sudo sh -c 'echo 127.0.1.1 gateway-01 >> /etc/hosts'
  - |
    sudo cat <<HOSTS > /etc/hosts
    127.0.0.1 localhost
    192.168.11.200 gateway-01.external gateway-01

    ::1     localhost ip6-localhost ip6-loopback
    ff02::1 ip6-allnodes
    ff02::2 ip6-allrouters

    192.168.8.10 controller-0
    192.168.8.11 controller-1
    192.168.8.12 controller-2
    192.168.8.20 worker-0
    192.168.8.21 worker-1
    192.168.8.22 worker-2
    HOSTS
  - echo "finish vm-setup.sh" > /home/debian/cloudinit-status.txt
  - reboot
EOF

qm set 9110 --cicustom "user=local:snippets/vm-setup.yaml"

# check the cloud-init config
qm cloudinit dump 9110 user

# create template and a linked clone
qm template 9110
qm clone 9110 $HOSTID --name gateway
qm destroy 9110
qm start $HOSTID

rm -rf debian-10.13.26-20240519-proxmox-amd64.qcow2